Fixes missing include error in bitcoin-core code.
Errors:

../../brave/third_party/bitcoin-core/src/src/crypto/sha256.cpp(519,19): error: no member named 'equal' in namespace 'std'
        if (!std::equal(state, state + 8, result[i])) return false;
             ~~~~~^
../../brave/third_party/bitcoin-core/src/src/crypto/sha256.cpp(525,15): error: no member named 'equal' in namespace 'std'
    if (!std::equal(out, out + 32, result_d64)) return false;
         ~~~~~^
../../brave/third_party/bitcoin-core/src/src/crypto/sha256.cpp(531,19): error: no member named 'equal' in namespace 'std'
        if (!std::equal(out, out + 64, result_d64)) return false;
             ~~~~~^
../../brave/third_party/bitcoin-core/src/src/crypto/sha256.cpp(538,19): error: no member named 'equal' in namespace 'std'
        if (!std::equal(out, out + 128, result_d64)) return false;
             ~~~~~^
../../brave/third_party/bitcoin-core/src/src/crypto/sha256.cpp(545,19): error: no member named 'equal' in namespace 'std'
        if (!std::equal(out, out + 256, result_d64)) return false;
             ~~~~~^
5 errors generated.